### ISSUE TITLE
Spots klick & wavelog integration choise

### ISSUE THREAD

**Issue by DL8JJ-Emil** [tnxqso/wave-flex-integrator#53]
Hello to all,
im Using the spots most of the time, just to click over and hear what happend on the QRG.
Than i can deside, if i want to call him or not.
Most of the time just click raound on the spots and the bands. 
On this situation i do not need every time that wavelog comming up. 

Perhaps a "single click" should not pop up the wavelog, later "double klick" -when i decide to work with the spot station should be connect the wavelog and put all infos into the live QSO window.

hw?
cheers
Emil

**Comment by besynnerlig** [comment]
Hi Emil,

Thanks for your input! As mentioned earlier, FlexRadio doesn’t support differentiating between single and double clicks, which limits our ability to change that behavior.

Regarding the request to disable Wave-Flex Integrator's response to clicked spots, this could be added as a setting. However, rather than toggling this setting each time, it might be simpler to just keep the Wavelogs logging tab in the browser minimized or hidden when you don't want to log directly. This avoids the need to update settings repeatedly and also reduces the risk of forgetting that the logging feature has been turned off.

For now, even if the Wavelog logging screen opens, you can just ignore it/hide it under a different browser tab without needing to save or complete any entries unless you actually decide to log the QSO.
